jwt:
  secret: ${JWT_SECRET} # Base64로 인코딩된 비밀키
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:900000}         # Access Token 유효기간 (15분, 밀리초 단위)
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:604800000}     # Refresh Token 유효기간 (7일, 밀리초 단위)

spring:
  application:
    name: be
  config:
    import: "optional:file:local.env"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Hibernate configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true   # 디버깅용이 아니라면 false로 설정
        hbm2ddl:
          auto: update  # 운영 환경에서는 create 대신 update 추천
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 30  # 운영 환경에서는 부하 테스트를 통해 조정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_TEST_CLIENT_ID}
            client-secret: ${KAKAO_TEST_CLIENT_SECRET}
            scope:
              - profile_nickname
#              - profile_image
              - account_email
              - phone_number
#              - shipping_address
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: id